# Generated by Django 2.2.12 on 2020-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='pin'),
        ),
    ]
