# Generated by Django 2.2.12 on 2020-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201110_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='custom_profile',
            field=models.CharField(blank=True, default='', help_text='Custom profile name/constant ONLY for clients with custom budgets', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_fees_profile',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
