# Generated by Django 2.2.12 on 2021-01-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201116_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='smsc_sender_name',
            field=models.CharField(blank=True, default='', help_text='SMSC sender name for sending SMS at every new onboarded entity by the standard vf model', max_length=11, null=True),
        ),
    ]
