# Generated by Django 2.2.12 on 2021-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_smsc_sender_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id', '-hierarchy'], 'permissions': (('can_disable_two_factor', 'the user can disable two factor'), ('can_use_two_factor_backup', 'the user can use two factor backup tokens'), ('can_use_two_factor', 'the user can use two factor'), ('has_disbursement', 'the client has disbursement options'), ('has_collection', 'the client has collection options'), ('has_instant_disbursement', 'the client/his children has instant disbursement capabilities'), ('can_view_api_docs', 'the user can view the api documentation'), ('vodafone_default_onboarding', 'the onboarding will be the old one at the super admin and the admin'), ('instant_model_onboarding', 'the onboarding of an instant entity will be only for the mandatory setups'), ('accept_vodafone_onboarding', 'the new vf & accept business model of no direct calls to the wallets'), ('vodafone_facilitator_accept_vodafone_onboarding', 'like our send business model but can only disburse for vodafone')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='client',
            name='agents_onboarding_choice',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New superagent and agents'), (1, 'Existing superagent and new agents'), (2, 'Existing superagent and agents'), (3, 'P2M')], db_index=True, default=0, verbose_name='Agents Onboarding Choice'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='mail_subject',
            field=models.CharField(blank=True, default='Paymob Send', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='smsc_sender_name',
            field=models.CharField(blank=True, default='', help_text='SMSC sender name for naming the header of the sms sent at every vf bulk disbursement request', max_length=11, null=True),
        ),
    ]
