# Generated by Django 2.2.12 on 2021-01-13 20:34

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210112_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vodafone_facilitator_identifier',
            field=models.CharField(blank=True, default='', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Vodafone facilitator unique identifier'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='entities_logo/send_new_logo.png', null=True, upload_to='entities_logo'),
        ),
    ]
