# Generated by Django 2.2.12 on 2021-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210113_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agents_onboarding_choice',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New superagent and new agents'), (1, 'Existing superagent and new agents'), (2, 'Existing superagent and existing agents'), (3, 'P2M Agent')], db_index=True, default=0, verbose_name='Agents Onboarding Choice'),
        ),
    ]
