# Generated by Django 2.2.12 on 2021-01-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210120_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id', '-hierarchy'], 'permissions': (('can_disable_two_factor', 'the user can disable two factor'), ('can_use_two_factor_backup', 'the user can use two factor backup tokens'), ('can_use_two_factor', 'the user can use two factor'), ('has_disbursement', 'the client has disbursement options'), ('has_collection', 'the client has collection options'), ('has_instant_disbursement', 'the client/his children has instant disbursement capabilities'), ('can_view_api_docs', 'the user can view the api documentation'), ('vodafone_default_onboarding', 'the onboarding will be the old one at the super admin and the admin'), ('instant_model_onboarding', 'the onboarding of an instant entity will be only for the mandatory setups'), ('accept_vodafone_onboarding', 'the new vf & accept business model of no direct calls to the wallets'), ('vodafone_facilitator_accept_vodafone_onboarding', 'like our send business model but can only disburse for vodafone'), ('banks_standard_model_onboaring', 'like default vodafone business model but disburse for raseedy')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
