# Generated by Django 2.2.12 on 2021-02-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210131_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.RootUser'),
        ),
    ]
