# Generated by Django 2.2.12 on 2021-02-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.RootUser'),
        ),
    ]
