# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/ambv/black
      rev: '22.3.0'
      hooks:
        - id: black
          language_version: python3.7.5
          args:
            - --skip-string-normalization
    - repo: https://github.com/timothycrosley/isort
      rev: '5.1.0'
      hooks:
        - id: isort
    - repo: https://github.com/humitos/mirrors-autoflake.git
      rev: 'v1.3'
      hooks:
        - id: autoflake
          args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports' ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-docstring-first
        - id: check-merge-conflict
        - id: check-json
        - id: debug-statements
          language_version: python3.7.5
        - id: mixed-line-ending
          args:
            - --fix=auto
