
from __future__ import absolute_import
try:
    from .key import SMSHOST_ENV, SMSPORT_ENV, SYSTEM_ID_ENV, SYSTEM_TYPE_ENV, PASSWORD_ENV, SMS_SENDER_HEADER_ENV, SMS_PROXY_ENV
    SMSHOST = SMSHOST_ENV
    SMSPORT = SMSPORT_ENV
    SYSTEM_ID = SYSTEM_ID_ENV
    SYSTEM_TYPE = SYSTEM_TYPE_ENV
    PASSWORD = PASSWORD_ENV
    SMS_SENDER_HEADER = SMS_SENDER_HEADER_ENV
    SMS_PROXY = SMS_PROXY_ENV
except ImportError:
    SMSHOST = ''
    SMSPORT = ''
    SYSTEM_ID = ''
    SYSTEM_TYPE = ''
    PASSWORD = ''
    SMS_SENDER_HEADER = ''
    SMS_PROXY = ''
