site_name: Payouts Portal Documentation!

docs_dir: 'mkdocs'
site_dir: '/app/mediafiles/mkdocs/build' # MKDOCS_ROOT_DIR
nav:
  - Home: index.md
  - Table Of Contents: table_of_contents.md
  - Definitions and Acronyms: definitions_and_acronyms.md
  - Generate and Refresh Token API: generate_and_refresh_token_api.md
  - Instant Cashin API: instant_cashin_api.md
  - Bulk Transaction Inquiry API: bulk_transaction_inquiry_api.md
  - Budget Inquiry API: budget_inquiry_api.md
  - Response Codes To Be Expected: response_codes_to_be_expected.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

extra:
    version: 2.0
