site_name: Payouts Portal Documentation!

docs_dir: 'mkdocs'
site_dir: '/app/payouts_portal/mkdocs_build' # MKDOCS_ROOT_DIR
nav:
  - Home: index.md
  - Table Of Contents: table_of_contents.md
  - Definitions and Acronyms: definitions_and_acronyms.md
  - Generate and Refresh Token API: generate_and_refresh_token_api.md
  - Instant Cashin API: instant_cashin_api.md
  - Cancel Aman Transaction API: cancel_aman_transaction_api.md
  - Bulk Transaction Inquiry API: bulk_transaction_inquiry_api.md
  - Budget Inquiry API: budget_inquiry_api.md
  - CallBack Url: callback_url.md
  - Response Codes: response_codes.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

markdown_extensions:
  - attr_list

extra:
    version: 2.0
