site_name: Payouts Portal Documentation!

docs_dir: 'mkdocs'
site_dir: 'MKDOCS_ROOT'
nav:
  - Home: index.md
  - Instant Cashin Integration: instant_payout_integration.md

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

extra:
    version: 1.1