# Generated by Django 2.2.12 on 2020-11-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('rrn', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Transaction Ref for the aggregator')),
                ('amount', models.FloatField(verbose_name='Paid Amount of Installment')),
                ('fine', models.FloatField(blank=True, default=0, null=True, verbose_name='Paid Fines of Installment')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Time of transaction')),
                ('status', models.SmallIntegerField(choices=[(0, 'Failure'), (1, 'Success')], default=1, verbose_name='Status')),
                ('type_of_payment', models.SmallIntegerField(choices=[(0, 'Full payment'), (1, 'Partial Payment'), (2, 'Over Payment')], default=0, verbose_name='Type of payment')),
                ('is_seen', models.BooleanField(default=False)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('file_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='data.FileData')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['datetime'],
                'get_latest_by': 'datetime',
            },
        ),
    ]
