# Generated by Django 2.2.12 on 2020-11-02 14:46

import data.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_partial_payment', models.BooleanField(default=0, help_text='If yes please mention the amount field below', verbose_name='Will there be partial payment?')),
                ('can_overpay', models.BooleanField(default=0, verbose_name='This user accept over payment?')),
                ('overflow_partial_acceptance_per_client', models.BooleanField(default=0, verbose_name='This biller accept over flow or partial per client?')),
                ('unique_field', models.CharField(max_length=128, verbose_name='What is the unique field?')),
                ('unique_field2', models.CharField(blank=True, max_length=128, verbose_name='What is the unique field?')),
                ('total_amount_field', models.CharField(blank=True, help_text='for ex: loan_field', max_length=128, verbose_name='what is total of loan amount field?')),
                ('payable_amount_field', models.CharField(help_text='For ex: Installment field', max_length=128, verbose_name='what is paid amount field?')),
                ('date_field', models.CharField(help_text="Don't write number of identifier, write the field itself", max_length=128, verbose_name='what is date field?')),
                ('mobile_field', models.CharField(blank=True, help_text='For ex: mobile_no, it can be one of the unique fields', max_length=128, null=True, verbose_name='what is Phone number field?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Collections' Data",
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'E-wallets'), (2, 'Collection'), (3, 'Bank wallets'), (4, 'Bank cards')], default=1, verbose_name='Type')),
                ('id', models.CharField(db_index=True, default=data.utils.pkgen, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=data.utils.update_filename)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('can_be_disbursed', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('txn_id', models.CharField(blank=True, max_length=16, null=True)),
                ('processing_failure_reason', models.CharField(max_length=256, null=True)),
                ('total_amount', models.FloatField(default=False)),
                ('total_count', models.PositiveIntegerField(default=False)),
                ('has_change_profile_callback', models.BooleanField(default=False, verbose_name='Has change profile callback?')),
                ('collection_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_doc', to='data.CollectionData')),
                ('disbursed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='users.CheckerUser', verbose_name='Disbursed by/Checker')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ('-created_at',),
                'permissions': (('upload_file', 'upload file'), ('delete_file', 'delete file'), ('download_file_xlsx', 'download xlsx file'), ('access_file', 'access file'), ('download_file_txt', 'download txt file'), ('edit_file_online', 'Edit the file online'), ('process_file', 'Can user process file data'), ('can_disburse', 'Can disburse file data')),
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 1')),
                ('identifier2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 2')),
                ('identifier3', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 3')),
                ('identifier4', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 4')),
                ('identifier5', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 5')),
                ('identifier6', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 6')),
                ('identifier7', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 7')),
                ('identifier8', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 8')),
                ('identifier9', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 9')),
                ('identifier10', models.CharField(blank=True, max_length=128, null=True, verbose_name='Header 10')),
                ('num_of_identifiers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Number of identifiers filled')),
                ('name', models.CharField(max_length=128, verbose_name='Description')),
                ('hierarchy', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, default=dict, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=0, verbose_name='Drafted')),
                ('is_downloaded', models.BooleanField(default=0)),
                ('has_full_payment', models.BooleanField(default=False)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filedata', to='data.Doc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'File Data',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Description')),
                ('unique_field', models.CharField(max_length=128, verbose_name='mobile number header position')),
                ('amount_field', models.CharField(help_text='For ex: loan_field', max_length=128, verbose_name='amount header position')),
                ('issuer_field', models.CharField(blank=True, help_text='Only activated at sheets with multiple issuers', max_length=128, null=True, verbose_name='issuer option header position')),
                ('no_of_reviews_required', models.PositiveSmallIntegerField(default=3, help_text='Number of reviews required for a doc with this file category to be disbursed', verbose_name='number of reviews')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_category', to='users.RootUser')),
            ],
            options={
                'verbose_name_plural': 'File Categories',
                'unique_together': {('user_created', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(default=False, help_text='Document is ok to be disbursed')),
                ('comment', models.CharField(blank=True, help_text='Empty if the review is ok', max_length=255, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='data.Doc')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CheckerUser')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='file_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='data.FileCategory'),
        ),
        migrations.AddField(
            model_name='doc',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.Format'),
        ),
        migrations.AddField(
            model_name='doc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to=settings.AUTH_USER_MODEL, verbose_name='Owner/Maker'),
        ),
    ]
