# Generated by Django 2.2.12 on 2020-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='type_of',
            field=models.PositiveSmallIntegerField(choices=[(1, 'E-wallets'), (2, 'Collection'), (3, 'Bank wallets'), (4, 'Bank cards')], db_index=True, default=1, verbose_name='Type'),
        ),
    ]
