# Generated by Django 2.2.12 on 2021-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201109_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='total_amount_with_fees_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total amount plus fees and VAT'),
        ),
    ]
