# Generated by Django 2.2.12 on 2021-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_doc_total_amount_with_fees_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
