# Generated by Django 2.2.12 on 2021-04-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_doc_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='doc',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
