# Generated by Django 2.2.12 on 2021-04-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210405_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='deleted',
        ),
    ]
