# Generated by Django 2.2.12 on 2021-04-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_doc_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='deleted_at',
        ),
    ]
