"""
Django settings for sharing project. Production settings

Generated by 'django-admin startproject' using Django 1.9.7.

"""

from .base import *

# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS += (
    'disbursement.paymobsolutions.com',
)

INSTALLED_APPS += (
    'django_extensions',
)

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bills_db',
        'USER': 'root',
        'PASSWORD': '_9jds_123Ljd!',
        'HOST': 'localhost',
        'PORT': '',
        'CONN_MAX_AGE': 600,
    }
}


#Email
SERVER_EMAIL = 'confirmrequest@paymobsolutions.com'
EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'email-smtp.eu-west-1.amazonaws.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'AKIAIBBG4EPQMH72VCEA'
EMAIL_HOST_PASSWORD = 'AmwPtRx02knXLgv+ERiFIE4vAJlA7Gy1oxUbAosUDBLr'

# Email Reporting

ADMINS = [('Amir Raouf', 'amirraouf@paymobsolutions.com'),
          ('Mostafa Menessy', 'menessy@paymobsolutions.com')
          ]
# celery

CELERY_BROKER_URL = 'amqp://paymobsecure:(!~)qwe!~@localhost//'

# ssl

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
