# Generated by Django 2.2.12 on 2020-11-02 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('P', 'Pending'), ('d', 'Default')], default='d', max_length=1, verbose_name='status')),
                ('anon_recipient', models.CharField(blank=True, max_length=14, null=True, verbose_name='Anonymous Recipient')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('issuer_type', models.CharField(blank=True, choices=[('V', 'Vodafone'), ('E', 'Etisalat'), ('O', 'Orange'), ('A', 'Aman'), ('B', 'Bank_Wallet')], db_index=True, max_length=1, null=True, verbose_name='Issuer Type')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction Reference')),
                ('anon_sender', models.CharField(blank=True, db_index=True, help_text="Agent used from Root's agents list", max_length=14, null=True, verbose_name='Sender')),
                ('transaction_status_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Status Code')),
                ('transaction_status_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status Description')),
                ('reference_id', models.CharField(default='', max_length=30, verbose_name='Reference ID')),
                ('recipient_name', models.CharField(blank=True, help_text='The customer/recipient name', max_length=70, null=True, verbose_name='Recipient Name')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instant_transaction', to='users.InstantAPICheckerUser', verbose_name='Instant API Checker')),
            ],
            options={
                'verbose_name': 'Instant Transaction',
                'verbose_name_plural': 'Instant Transactions',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': '-updated_at',
            },
        ),
        migrations.CreateModel(
            name='AmanTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False, help_text='Updated at every notify_merchant_callback if the transaction is successfully paid', verbose_name='Is Paid?')),
                ('bill_reference', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Bill Reference')),
                ('transaction_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Aman Transaction',
                'verbose_name_plural': 'Aman Transactions',
                'get_latest_by': '-id',
            },
        ),
    ]
