# Generated by Django 2.2.12 on 2020-11-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201109_1918'),
        ('instant_cashin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanttransaction',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_wallets_transactions', to='data.Doc', verbose_name='Disbursement Document'),
        ),
        migrations.AlterField(
            model_name='instanttransaction',
            name='issuer_type',
            field=models.CharField(blank=True, choices=[('V', 'Vodafone'), ('E', 'Etisalat'), ('O', 'Orange'), ('A', 'Aman'), ('B', 'Bank_Wallet'), ('C', 'Bank_Card')], db_index=True, max_length=1, null=True, verbose_name='Issuer Type'),
        ),
    ]
