# Generated by Django 2.2.12 on 2020-11-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instant_cashin', '0002_auto_20201110_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanttransaction',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_wallets_transactions', to='data.Doc', verbose_name='Bank Wallets Document'),
        ),
    ]
