# Generated by Django 2.2.12 on 2021-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_cashin', '0003_auto_20201116_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanttransaction',
            name='is_single_step',
            field=models.BooleanField(default=False, verbose_name='Is manual patch single step transaction?'),
        ),
    ]
