# Generated by Django 2.2.12 on 2021-04-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_cashin', '0004_instanttransaction_is_single_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanttransaction',
            name='disbursed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disbursed At'),
        ),
    ]
