# Generated by Django 2.2.12 on 2020-11-02 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VMTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_username', models.CharField(max_length=32, verbose_name='UIG Login Username')),
                ('login_password', models.CharField(max_length=32, verbose_name='UIG Login Password')),
                ('request_gateway_code', models.CharField(max_length=32, verbose_name='UIG Request Gateway Code')),
                ('request_gateway_type', models.CharField(max_length=32, verbose_name='UIG Request Gateway Type')),
                ('wallet_issuer', models.CharField(max_length=64, verbose_name='UIG Wallet Issuer')),
                ('vmt_environment', models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('STAGING', 'STAGING'), ('DEVELOPMENT', 'DEVELOPMENT')], max_length=16, verbose_name='VMT Environment')),
                ('vmt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vmt', to='users.SuperAdminUser', verbose_name='VMT Credentials Owner')),
            ],
            options={
                'verbose_name': 'VMT Credential',
                'verbose_name_plural': 'VMT Credentials',
            },
        ),
        migrations.CreateModel(
            name='DisbursementDocData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('txn_id', models.CharField(blank=True, max_length=16, null=True)),
                ('txn_status', models.CharField(blank=True, max_length=16, null=True)),
                ('has_callback', models.BooleanField(default=False, verbose_name='Has Callback?')),
                ('doc_status', models.CharField(choices=[('d', 'Default'), ('1', 'Uploaded Successfully'), ('2', 'Processing Failure'), ('3', 'Processed Successfully'), ('4', 'Disbursement Failure'), ('5', 'Disbursed Successfully')], default='d', max_length=1, verbose_name='Document disbursement status')),
                ('doc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_txn', to='data.Doc')),
            ],
            options={
                'verbose_name': 'Disbursement Document',
                'verbose_name_plural': 'Disbursement Documents',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('P', 'Pending'), ('d', 'Default')], default='d', max_length=1, verbose_name='status')),
                ('currency', models.CharField(choices=[('EGP', 'Egyptian Pound')], default='EGP', max_length=3, verbose_name='Currency')),
                ('category_code', models.CharField(choices=[('CASH', 'General cash'), ('LIMA', 'Onus direct debit'), ('LPRT', 'LPRT'), ('MOBI', 'Mobile payment'), ('PCRD', 'PrePaid card'), ('PENS', 'Payment of pension'), ('SALA', 'Payment of salaries'), ('USD', 'USD transaction')], default='CASH', help_text='Type of the sending remittance', max_length=4, verbose_name='Category Code')),
                ('purpose', models.CharField(choices=[('CASH', 'حوالات - Cash Transfer'), ('INST', 'أقساط - Installment'), ('PAYR', 'مرتبات - Payroll'), ('SUPP', 'موردين - Supplier Payment'), ('COLL', 'كمبيالات - Collection'), ('CCRD', 'بطاقة إئتمان - Credit Card'), ('COLT', 'متحصلات - COLT'), ('PENS', 'Transaction is the payment of pension - معاشات - Pension'), ('ACCT', 'Transaction moves funds between 2 accounts of same account holder'), ('SALA', 'Transaction is the payment of salaries'), ('OTHR', 'Other payment purpose')], default='CASH', max_length=4, verbose_name='Purpose')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='New one generated everytime send_trx request made to EBC', unique=True, verbose_name='Transaction ID')),
                ('message_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='New one generated everytime send_trx or get_trx_status request made to EBC', unique=True, verbose_name='Message ID')),
                ('transaction_status_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Transaction Status Code')),
                ('transaction_status_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction Status Description')),
                ('debtor_account', models.CharField(help_text='The company/service provider account number', max_length=34, verbose_name='Corporate Account Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('creditor_name', models.CharField(help_text='The customer/receiver name', max_length=70, verbose_name='Beneficiary Name')),
                ('creditor_account_number', models.CharField(help_text='The customer/receiver bank account', max_length=34, verbose_name='Beneficiary Account Number')),
                ('creditor_bank', models.CharField(help_text='The bank where the customer/receiver maintains its accounts', max_length=11, verbose_name='Beneficiary Bank')),
                ('creditor_bank_branch', models.CharField(blank=True, default='', max_length=35, verbose_name='Beneficiary Bank Branch')),
                ('end_to_end', models.CharField(blank=True, default='', max_length=36, verbose_name='Optional Transaction Identifier 1')),
                ('creditor_email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Beneficiary Email')),
                ('creditor_mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EG', verbose_name='Beneficiary Mobile Number')),
                ('corporate_code', models.CharField(help_text='Corporate Code to identify corporate', max_length=50, verbose_name='Corporate Code')),
                ('sender_id', models.CharField(blank=True, default='', max_length=35, verbose_name='Sender ID')),
                ('creditor_id', models.CharField(blank=True, default='', max_length=35, verbose_name='Creditor ID')),
                ('creditor_address_1', models.CharField(blank=True, default='', max_length=70, verbose_name='Creditor Address 1')),
                ('debtor_address_1', models.CharField(blank=True, default='', max_length=70, verbose_name='Debtor Address 1')),
                ('additional_info_1', models.CharField(blank=True, default='', max_length=140, verbose_name='Remittance Info 1')),
                ('parent_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_transactions', to='disbursement.BankTransaction', verbose_name='Parent Transaction')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Disburser')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': '-created_at',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=14, verbose_name='Mobile number')),
                ('pin', models.BooleanField(default=False)),
                ('super', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('V', 'vodafone'), ('E', 'etisalat'), ('O', 'orange')], db_index=True, default='V', max_length=1, verbose_name='agent type')),
                ('wallet_provider', models.ForeignKey(help_text='Each super-agent or agent MUST be related to specific Root user', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('is_disbursed', models.BooleanField(default=0)),
                ('amount', models.FloatField(verbose_name='AMOUNT')),
                ('msisdn', models.CharField(max_length=16, verbose_name='Mobile Number')),
                ('issuer', models.CharField(db_index=True, default='default', max_length=8, verbose_name='Issuer Option')),
                ('reason', models.TextField()),
                ('reference_id', models.CharField(default='None', max_length=30, verbose_name='Reference ID')),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_data', to='data.Doc')),
            ],
            options={
                'verbose_name': 'Disbursement Data Record',
                'verbose_name_plural': 'Disbursement Data Records',
                'get_latest_by': ['id'],
                'unique_together': {('doc', 'msisdn')},
                'index_together': {('doc', 'msisdn')},
            },
        ),
    ]
