# Generated by Django 2.2.12 on 2020-11-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0002_auto_20201109_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='document',
        ),
    ]
