# Generated by Django 2.2.12 on 2020-11-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201109_1918'),
        ('disbursement', '0003_remove_banktransaction_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards_transactions', to='data.Doc', verbose_name='Bank Cards Document'),
        ),
    ]
