# Generated by Django 2.2.12 on 2020-11-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0005_banktransaction_is_single_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='is_single_step',
        ),
    ]
