# Generated by Django 2.2.12 on 2020-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0006_remove_banktransaction_is_single_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_single_step',
            field=models.BooleanField(default=False, verbose_name='Is manual patch single step transaction?'),
        ),
    ]
