# Generated by Django 2.2.12 on 2021-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0008_auto_20201222_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('V', 'vodafone'), ('E', 'etisalat'), ('O', 'orange'), ('P', 'P2M')], db_index=True, default='V', max_length=1, verbose_name='agent type'),
        ),
    ]
