# Generated by Django 2.2.12 on 2021-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0009_auto_20210120_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementdata',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
