# Generated by Django 2.2.12 on 2021-04-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0010_disbursementdata_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementdata',
            name='deleted',
        ),
    ]
