# Generated by Django 2.2.12 on 2021-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0011_remove_disbursementdata_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='disbursed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disbursed At'),
        ),
        migrations.AddField(
            model_name='disbursementdata',
            name='disbursed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Disbursed At'),
        ),
    ]
