# Generated by Django 2.2.12 on 2021-04-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210228_1910'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0002_auto_20201123_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBudget',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated At')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Updated automatically after any disbursement callback or any addition from add_new_amount', max_digits=10, null=True, verbose_name='Current Balance')),
                ('total_disbursed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Updated automatically after any disbursement callback', max_digits=15, verbose_name='Total Disbursed Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Super Admin who created/updated this budget values', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.SuperAdminUser', verbose_name='Maintainer - Super Admin')),
                ('disburser', models.ForeignKey(blank=True, db_constraint=False, help_text='Before every cashin transaction, the amount to be disbursed will be validated against the current balance of the (API)-Checker owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.RootUser', verbose_name='Owner/Admin of the Disburser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Custom Budget',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
